name: Build & Push Backend

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Decode application.properties from secret
        run: |
          echo "${{ secrets.APP_PROPERTIES_BASE64 }}" | base64 --decode > src/main/resources/application.properties

      - run: ./gradlew bootJar --no-daemon

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/com2here/com2here_back:latest