name: Build & Push Backend

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: ./gradlew bootJar --no-daemon
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/Com2here/com2here_back:latest
